### ISSUE TITLE
Release Path not created

### ISSUE THREAD

**Issue by Hounddog** [seattlerb/vlad#24]
Am not able to run an update as it seems the release path is not generated. Have put together a comple console output 

<pre>
mshwalbe@schuttgart:/var/www/mshwalbe/V5/src$ ls -al ../../v5_test_deploy/
total 8
drwxrwxr-x  2 mshwalbe adm          4096 Jul  5 17:46 .
drwxr-xr-x 29 mshwalbe developpeurs 4096 Jul  5 14:51 ..
mshwalbe@schuttgart:/var/www/mshwalbe/V5/src$ rake vlad:setup
mshwalbe@schuttgart:/var/www/mshwalbe/V5/src$ ls -al ../../v5_test_deploy/
total 20
drwxrwxr-x  5 mshwalbe adm          4096 Jul  5 17:47 .
drwxr-xr-x 29 mshwalbe developpeurs 4096 Jul  5 14:51 ..
drwxrwxr-x  2 mshwalbe adm          4096 Jul  5 17:47 releases
drwxrwxr-x  2 mshwalbe adm          4096 Jul  5 17:47 scm
drwxrwxr-x  5 mshwalbe adm          4096 Jul  5 17:47 shared
mshwalbe@schuttgart:/var/www/mshwalbe/V5/src$ ls -al ../../v5_test_deploy/releases/
total 8
drwxrwxr-x 2 mshwalbe adm 4096 Jul  5 17:47 .
drwxrwxr-x 5 mshwalbe adm 4096 Jul  5 17:47 ..
mshwalbe@schuttgart:/var/www/mshwalbe/V5/src$ rake vlad:update --trace
** Invoke vlad:update (first_time)
** Execute vlad:update
ssh php5.dys1.net 'if cd /var/www/mshwalbe/v5_test_deploy/scm/repo && git rev-parse HEAD && git remote -v | grep -q ssh://git.doyousoft.com/srv/git/retd/V5.git && cd -; then exit 0; else exit 1; fi &>/dev/null'
ssh php5.dys1.net 'umask 02 && cd /var/www/mshwalbe/v5_test_deploy/scm && rm -rf /var/www/mshwalbe/v5_test_deploy/scm/repo && git clone ssh://git.doyousoft.com/srv/git/retd/V5.git /var/www/mshwalbe/v5_test_deploy/scm/repo && cd /var/www/mshwalbe/v5_test_deploy/scm/repo && git submodule init && git submodule update && git checkout -f -b deployed-HEAD HEAD && cd - && mkdir -p /var/www/mshwalbe/v5_test_deploy/releases/20120705154716 && cd repo && git archive --format=tar deployed-HEAD | (cd /var/www/mshwalbe/v5_test_deploy/releases/20120705154716 && tar xf -) && git submodule foreach 'git archive --format=tar $sha1 | (cd /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/$path && tar xf -)' && cd - && cd .. && chmod -R g+w /var/www/mshwalbe/v5_test_deploy/releases/20120705154716 && rm -rf /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/public/system /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/log /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/tmp/pids && mkdir -p /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/tmp /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/db'
Cloning into /var/www/mshwalbe/v5_test_deploy/scm/repo...
Switched to a new branch 'deployed-HEAD'
/var/www/mshwalbe/v5_test_deploy/scm
/var/www/mshwalbe/v5_test_deploy/scm
** Invoke vlad:update_symlinks (first_time)
** Execute vlad:update_symlinks
ssh php5.dys1.net 'ln -s /var/www/mshwalbe/v5_test_deploy/shared/system /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/public/system && ln -s /var/www/mshwalbe/v5_test_deploy/shared/log /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/log && ln -s /var/www/mshwalbe/v5_test_deploy/shared/pids /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/tmp/pids'
ln: création d'un lien symbolique « /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/public/system »: Aucun fichier ou dossier de ce type
ssh php5.dys1.net 'rm -rf /var/www/mshwalbe/v5_test_deploy/releases/20120705154716'
rake aborted!
execution failed with status 1: ssh php5.dys1.net ln -s /var/www/mshwalbe/v5_test_deploy/shared/system /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/public/system && ln -s /var/www/mshwalbe/v5_test_deploy/shared/log /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/log && ln -s /var/www/mshwalbe/v5_test_deploy/shared/pids /var/www/mshwalbe/v5_test_deploy/releases/20120705154716/tmp/pids
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:222:in `run'
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:638:in `join'
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:638:in `execute'
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:638:in `each'
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:638:in `execute'
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:116:in `execute'
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:116:in `each'
/var/lib/gems/1.8/gems/rake-remote_task-2.0.6/lib/rake/remote_task.rb:116:in `execute'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/var/lib/gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/var/lib/gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/var/lib/gems/1.8/bin/rake:19:in `load'
/var/lib/gems/1.8/bin/rake:19
Tasks: TOP => vlad:update_symlinks
mshwalbe@schuttgart:/var/www/mshwalbe/V5/src$ ls -al ../../v5_test_deploy/releases/
total 8
drwxrwxr-x 2 mshwalbe adm 4096 Jul  5 17:47 .
drwxrwxr-x 5 mshwalbe adm 4096 Jul  5 17:47 ..
mshwalbe@schuttgart:/var/www/mshwalbe/V5/src$ 
</pre>

**Comment by zenspider** [comment]
Closing stale bug. Please reopen if you feel otherwise.
