### ISSUE TITLE
SSH through gateway fails with multiple commands (as in vlad:setup)

### ISSUE THREAD

**Issue by pmahoney** [seattlerb/vlad#28]
Given the following configuration

    remote_task :vlad_with_gateway do
      run 'umask 02 && hostname'
    end

    set :domain ['target_host']
    set :ssh_flags, ['-A', 'gateway', 'ssh', '-A']

The rake task fails because the second command (`hostname`) is actually run on the gateway host    

    $ rake --trace vlad_with_gateway
    ** Invoke vlad_with_gateway (first_time)
    ** Execute vlad_with_gateway
    ssh -A gateway ssh -A target_host 'umask 02 && hostname'
    gateway

This is a similar command to what `vlad:setup` runs, though the above example makes it clear on which host the `hostname` command is being run.

The issue is one of quoting, I think.  The command is parsed as `ssh -A gateway ((ssh -A target_host umask) && hostname)`.  Hacking `rake-remote_task` to use `command.inspect` rather than `command` in its `run` method seems to solve the problem, but I'm not sure that is the best solution (is the quoting added by `#inspect` compatible with the shell in all cases?).

Another option is to make two calls to ssh: the first sets up a port forward from the current host to the target_host via the gateway.  The second runs the ssh command (without any extra `ssh_flags`), pointing ssh to that port forward.  (See [11.5.3. Another Approach: SSH-in-SSH(Port Forwarding)](http://csce.uark.edu/~kal/info/private/Networking%20Bookshelf/ssh/ch11_05.htm)).  This looks like it would be a significant amount of work though.  It's also possible to just require users of vlad to setup up such a port forward manually.

On the other hand, if the quotes added by the `#inspect` method solves the 80%, it may be the way to go to keep the simple spirit of vlad.

**Comment by zenspider** [comment]
Stale. Closing.
