### ISSUE TITLE
Race condition in vlad:update when doing multi-server deploys

### ISSUE THREAD

**Issue by jaswope** [seattlerb/vlad#34]
If you are running vlad:update in a multi-server deploy, you can get a failure saying vlad:update_symlinks was unable to create the symlinks.  This is because remote rake tasks are executed in parallel to all hosts in the assigned roles, and the remote task vlad:update_symlinks is [invoked in the middle of vlad:update](https://github.com/seattlerb/vlad/blob/master/lib/vlad/core.rb#L91).  So if one of the servers being deployed to isn't done with its SCM activity when update_symlinks is called in the first server's tasks, the entire task will fail with the above message.

The obvious solution would be to defer the call to update_symlinks until after update is done for all servers, however the implementation of such could be tricky to do while preserving the same expected functionality.

**Comment by zenspider** [comment]
Seems handled by above comment. Closing.
