### ISSUE TITLE
Domain expired - http://rubyhitsquad.com/

### ISSUE THREAD

**Issue by khromov** [seattlerb/vlad#57]
http://rubyhitsquad.com/

**Comment by zenspider** [comment]
Yup. Fixed urls. Thanks!

**Comment by khromov** [comment]
@zenspider Seems one slipped past: https://github.com/seattlerb/vlad/blob/master/README.txt#L3

**Comment by zenspider** [comment]
> On Aug 14, 2015, at 14:13, Stanislav Khromov <notifications@github.com> wrote:
> 
> @zenspider Seems one slipped past: https://github.com/seattlerb/vlad/blob/master/README.txt#L3

nope. just hadn't mirrored to git yet.
